### ISSUE TITLE
0.11.x  Missing complementary exercises

### ISSUE THREAD

**Issue by G-Pereira** [FEUP-MIEEC/Prog2#1]
O último exercicio da ficha de revisões está incompleto devido à sua complexidade. @Dannyps @Hyrokumata please help

Exercício 11:
- [x] ADDREV
- [x] HELLOKIT
- [ ] TOANDFRO
- [ ] BITMAP
- [ ] STPAR

**Comment by Dannyps** [comment]
Eu não sabia que já tinhas encontrado esta ficha o.O

Hoje não tenho disponibilidade xD

**Comment by Hyrokumata** [comment]
@G-Pereira o teu ADDREV não está de acordo como eles querem. Ou seja, o output não está correto. Primeiro lês o input, todos os pares de números. Quando terminar, então fazes o output. O teu lê input e imprime o resultado de seguida, o que reduz a dificuldade do problema :smile:

**Comment by Dannyps** [comment]
Ainda não olhei para isto. Temos de começar a incentivar Pull Requests, gente!

**Comment by fabiodrg** [comment]
Esta madrugada fica pronto!! Comecei o TOANDFRO, mas ainda não acabei. Se alguém estiver inspirado, DO IT

**Comment by Dannyps** [comment]
Neste momento, estou mais focado em acabar os da última aula prática. Boa sorte :)
