### ISSUE TITLE
Aula 3 -> Extras Exercicio 1 = confuso

### ISSUE THREAD

**Issue by G-Pereira** [FEUP-MIEEC/Prog2#2]
- [ ] A
- [ ] C
- [ ] D
- [ ] E
- [ ] F
- [ ] G

**Comment by G-Pereira** [comment]
Alguém com paciência por estes lados?

**Comment by fabiodrg** [comment]
Tenho dois exercícios em curso. Talvez pegue nisto ainda hoje
