### ISSUE TITLE
MT2_P2

### ISSUE THREAD

**Issue by Igofuturo** [FEUP-MIEEC/Prog2#4]
Boas, eu estava a tentar fazer o exercício 2 do MT2 e falta apenas a parte de ordenar

Já tentei da maneira que está aqui no exemplo mas não funcionou, o código está correto?

O problema que o eclipse mostrou foi na linha 20 "jogador temp"...

**Comment by fabiodrg** [comment]
@Igofuturo não há qualquer erro. Está correto. Nessa linha é declarada uma variável tmp que é do tipo <strong>struct jogador</strong>. Se o eclipse dá erro aí, está bêbado. O clang não se queixa de nada, nem faria sentido.. é uma mera declaração de variável.

**Comment by Dannyps** [comment]
Estava a resolver esse exercício e não reparei na estrutura `jogador`. Que trabalheira que eu tive xD

```
jogador* conta_vitorias(FILE* f, int *njogadores)
{
    int linhas, i, j, c=0, encontrei;
    char str[50];
    char ch;
    while(!feof(f))
    {
        ch = fgetc(f);
        if(ch == '\n')
            linhas++;
    }
    char** nomes=malloc(sizeof(char**)*linhas);
    int* vitorias=malloc(sizeof(int)*linhas);

    fseek(f, 0, SEEK_SET);

    for(i=0;i<linhas;i++){
        encontrei=0;
        fgets(str, 50, f);
        for(j=0; j<c; j++){
            if(strcmp(nomes[j], str)==0){
                encontrei=1;
                break;
            }
        }
        if(encontrei){
            vitorias[j]++;
        }else{
            nomes[j]=malloc(sizeof(char)*(strlen(str)+1));
            strcpy(nomes[j], str);
            vitorias[j]=1;
            c++;
        }
    }

    //......

    return NULL;
}
```

felizmente não acabei.

**Comment by fabiodrg** [comment]
:facepalm: xD
